{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-test-junit",
    "version": "1.9.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "junitApi",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-test-junit-1.9.24.jar",
          "url": "kotlin-test-junit-1.9.24.jar",
          "size": 5140,
          "sha512": "0db55f56b5b1f4c4e32ac231fcf629bd9a48ceb82a2518df2bfdc51728bd9adecd8c19c68805a9d6e9cbbe61d83da18ad3193653e31f77f24c5ecdb7ace586eb",
          "sha256": "cafc7ffc791e7e79516afe0e8809ad7e4cdb3844a485246727705494da4f9e03",
          "sha1": "bc3c3133bd2a2e35fdf0e4324bd12dea846d1b52",
          "md5": "5b67d192113f660d95bb80ef66d398c6"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-impl",
          "version": "1.9.24"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-junit",
          "version": "1.9.24"
        }
      ]
    },
    {
      "name": "junitRuntime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-test-junit-1.9.24.jar",
          "url": "kotlin-test-junit-1.9.24.jar",
          "size": 5140,
          "sha512": "0db55f56b5b1f4c4e32ac231fcf629bd9a48ceb82a2518df2bfdc51728bd9adecd8c19c68805a9d6e9cbbe61d83da18ad3193653e31f77f24c5ecdb7ace586eb",
          "sha256": "cafc7ffc791e7e79516afe0e8809ad7e4cdb3844a485246727705494da4f9e03",
          "sha1": "bc3c3133bd2a2e35fdf0e4324bd12dea846d1b52",
          "md5": "5b67d192113f660d95bb80ef66d398c6"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-impl",
          "version": "1.9.24"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-junit",
          "version": "1.9.24"
        }
      ]
    }
  ]
}
