apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: egovframe-template
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root1234
  MYSQL_PASSWORD: pst01
