apiVersion: v1
kind: Service
metadata:
  name: egov-portal-site
  labels:
    app.kubernetes.io/name: egov-portal-site
    app.kubernetes.io/part-of: egovframe-template
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: egov-portal-site
  ports:
    - name: http
      port: 8080
      targetPort: http
